### ISSUE TITLE
tsm problems

### ISSUE THREAD

**Issue by prytosan** [grepsedawk/tsm-groups#4]
Welcome
I`ve tried to import Your`s tsm settings :(. All the time getting inf that min price is invalid.

**Comment by grepsedawk** [comment]
The installation directions are clearly documented in the README.
You can find the installation directions in the README here: https://github.com/grepsedawk/tsm-groups#installationimport

**Comment by prytosan** [comment]
Yes Się ... all istnieje clear. I did like was written but i've got this.
(Picture added)

wt., 12 lis 2019, 18:22 użytkownik Alex Piechowski <notifications@github.com>
napisał:
